### ISSUE TITLE
Can't use hostname for MAIL_SMTP_HOST env var

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#279]

**Comment by Krakaw** [comment]
Need to be able to set MAIL_SMTP_HOST to either an IP or "smtp.gmail.com"

**Comment by SWvheerden** [comment]
works with localhost and 127.0.0.1

**Comment by Krakaw** [comment]
thread 'arbiter:c4ea1f19-6be1-4280-8b26-f131643f3295:actor' panicked at 'Failed to create transport: Io(Custom { kind: Other, error: StringError("failed to lookup address information: Name or service not known") })', libcore/result.rs:945:5
api_1      | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
api_1      | stack backtrace:
api_1      |    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
api_1      |              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
api_1      |    1: std::sys_common::backtrace::print
api_1      |              at libstd/sys_common/backtrace.rs:71
api_1      |              at libstd/sys_common/backtrace.rs:59
api_1      |    2: std::panicking::default_hook::{{closure}}
api_1      |              at libstd/panicking.rs:211
api_1      |    3: std::panicking::default_hook
api_1      |              at libstd/panicking.rs:227
api_1      |    4: std::panicking::rust_panic_with_hook
api_1      |              at libstd/panicking.rs:475
api_1      |    5: std::panicking::continue_panic_fmt
api_1      |              at libstd/panicking.rs:390
api_1      |    6: rust_begin_unwind
api_1      |              at libstd/panicking.rs:325
api_1      |    7: core::panicking::panic_fmt
api_1      |              at libcore/panicking.rs:77
api_1      |    8: core::result::unwrap_failed
api_1      |    9: <bigneon_api::mail::transports::smtp_transport::SmtpTransport as bigneon_api::mail::transports::transport::Transport>::send
api_1      |   10: bigneon_api::mail::mailers::mailer::Mailer::deliver
api_1      |   11: bigneon_api::controllers::organization_invites::create
api_1      |   12: <F as actix_web::with::FnWith<T, R>>::call_with
api_1      |   13: <actix_web::with::WithHandlerFut<T, S, R> as futures::future::Future>::poll
api_1      |   14: <actix_web::route::Compose<S> as futures::future::Future>::poll
api_1      |   15: <actix_web::pipeline::PipelineState<S, H>>::poll
api_1      |   16: <actix_web::pipeline::Pipeline<S, H> as actix_web::server::HttpHandlerTask>::poll_io
api_1      |   17: <actix_web::server::h1::Http1<T, H>>::poll_handler
api_1      |   18: <actix_web::server::h1::Http1<T, H>>::poll
api_1      |   19: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
api_1      |   20: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
api_1      |   21: futures::task_impl::std::set
api_1      |   22: tokio_current_thread::CurrentRunner::set_spawn
api_1      |   23: <tokio_current_thread::scheduler::Scheduler<U>>::tick
api_1      |   24: <tokio_current_thread::Entered<'a, P>>::block_on
api_1      |   25: <std::thread::local::LocalKey<T>>::with
api_1      |   26: <std::thread::local::LocalKey<T>>::with
api_1      |   27: <std::thread::local::LocalKey<T>>::with
api_1      |   28: <std::thread::local::LocalKey<T>>::with
api_1      |   29: tokio::runtime::current_thread::runtime::Runtime::block_on

**Comment by philipr-za** [comment]
This is going to be a tough one to debug. It has got to be something to do with the way the docker environment is handling the creation of sockets. I did take a short stab at recreating the issue and I think it has something to do with the Docker network stack wanting to resolve addresses into IP6 format which the Rust mail library is freaking out about.

**Comment by Krakaw** [comment]
@philipr-za I've even tried with an IPV4 address? One thing that maybe we should make a new issue, is let's make the call asynchronous (nobody wants to wait for SMTP to complete) as well as stopping a panic / crash.

**Comment by mikethetike** [comment]
@Krakaw what was the error with the IPV4 address. There's definitely a bug with IP6 at the moment in the libraries we're using

**Comment by SWvheerden** [comment]
pr #413 moves the email to a best effort case. 
This will stop the error from panicing the main thread.
