### ISSUE TITLE
After updating the fee schedule adding to cart fails

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#596]
```
thread 'arbiter:cab3832d-4c24-44d6-b868-fe2ee81733e3:actix-net-worker-0' panicked at 'assertion failed: index < len', liballoc/vec.rs:888:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: bigneon_db::models::orders::Order::update_quantities
  10: bigneon_api::controllers::cart::update_cart
  11: <F as actix_web::with::FnWith<T, R>>::call_with
  12: <actix_web::with::WithHandlerFut<T, S, R> as futures::future::Future>::poll
  13: <actix_web::route::Compose<S> as futures::future::Future>::poll
  14: <actix_web::pipeline::PipelineState<S, H>>::poll
  15: <actix_web::pipeline::Pipeline<S, H> as actix_web::server::handler::HttpHandlerTask>::poll_io
  16: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll_handler
  17: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll
  18: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
  19: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
  20: <actix_net::service::and_then::AndThenFuture<A, B> as futures::future::Future>::poll
  21: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
  22: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  23: futures::task_impl::std::set
  24: tokio_current_thread::CurrentRunner::set_spawn
  25: <tokio_current_thread::scheduler::Scheduler<U>>::tick
  26: <tokio_current_thread::Entered<'a, P>>::block_on
  27: <std::thread::local::LocalKey<T>>::with
  28: <std::thread::local::LocalKey<T>>::with
  29: <std::thread::local::LocalKey<T>>::with
  30: <std::thread::local::LocalKey<T>>::with
  31: tokio::runtime::current_thread::runtime::Runtime::block_on
```

**Comment by Timo614** [comment]
@krakaw having some trouble reproducing, I'll take a look at the code to see if anything stands out (it's too bad there aren't line numbers for update_quantities call as it's a pretty big method). Do you know if there's something specific about the values you used that perhaps I'm not causing?

I've been trying by:

1. Update quantities in the cart for a ticket type
2. Call the add schedules method for an event to add new schedules
3. Update quantities in the cart for the same ticket type again

```
curl --header "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3Njg0NjQyOS1hMTQyLTQ0ZmQtODQxNS04YmM3OTczY2NkMTQiLCJpc3MiOiJiZy1zYW1wbGUtaXNzdWVyIiwiZXhwIjoxNTQzNDQ3MDQwfQ.JYjmPVjkfM6HupSw3EVqud-6qo8IUY6K6JzxYYCGOZM" -X POST --data '{"items": [{"ticket_type_id": "d6e31698-5ccf-416c-8347-d4decc0c80b5", "quantity": 4}]}' http://localhost:9000/cart  --header "Content-Type: application/json" -i --header "Host: localhost:9000"
HTTP/1.1 200 OK
content-length: 1022
content-type: application/json
access-control-allow-origin: http://localhost:3000
vary: Origin
x-app-version: 0.1.0
date: Wed, 28 Nov 2018 23:11:57 GMT

{"id":"92b1570b-e6ae-4829-bb03-3bca4bfc1ea5","date":"2018-11-28T23:08:11.441830","expires_at":"2018-11-28T23:23:11.456329","seconds_until_expiry":673,"status":"Draft","items":[{"id":"0dbbe93f-5a1f-400a-a623-42d02997a68d","parent_id":null,"ticket_type_id":"d6e31698-5ccf-416c-8347-d4decc0c80b5","ticket_pricing_id":"3a9449fb-60a0-46c1-a3fa-5ee6d3f0bd31","quantity":4,"unit_price_in_cents":3000,"item_type":"Tickets","description":"It's my party - General Admission_1543444451","redemption_code":null},{"id":"58099cc3-1534-48c9-ba4f-de619a78e28a","parent_id":"0dbbe93f-5a1f-400a-a623-42d02997a68d","ticket_type_id":null,"ticket_pricing_id":null,"quantity":4,"unit_price_in_cents":10,"item_type":"PerUnitFees","description":"Ticket Fees","redemption_code":null},{"id":"465eec36-7df0-45cf-99fe-a1822fc94e31","parent_id":null,"ticket_type_id":null,"ticket_pricing_id":null,"quantity":1,"unit_price_in_cents":100,"item_type":"EventFees","description":"Event Fees - It's my party","redemption_code":null}],"total_in_cents":12140}

curl --header "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3Njg0NjQyOS1hMTQyLTQ0ZmQtODQxNS04YmM3OTczY2NkMTQiLCJpc3MiOiJiZy1zYW1wbGUtaXNzdWVyIiwiZXhwIjoxNTQzNDQ4ODQ5fQ.NLbJFb3o1EhhtWrKsx1FIB-I7BLMMoS3-SMjVAcuIMc" -X POST --data '{"name": "New Schedule", "ranges": [{"min_price": 100, "fee_in_cents": 10}]}' http://localhost:9000/organizations/e2470ec2-8af2-4fa1-861e-d2e28340897b/fee_schedule  --header "Content-Type: application/json" -i --header "Host: localhost:9000"
HTTP/1.1 201 Created
content-length: 353
content-type: application/json
access-control-allow-origin: http://localhost:3000
vary: Origin
x-app-version: 0.1.0
date: Wed, 28 Nov 2018 23:33:04 GMT

{"id":"07fb2335-c635-4f20-b8c3-9525b53b1e93","name":"New Schedule","version":0,"created_at":"2018-11-28T23:33:04.655296","ranges":[{"id":"845b515b-7096-4a35-95f5-eefe6a23f51b","fee_schedule_id":"07fb2335-c635-4f20-b8c3-9525b53b1e93","min_price":100,"fee_in_cents":10,"created_at":"2018-11-28T23:33:04.655296","updated_at":"2018-11-28T23:33:04.655296"}]}

curl --header "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3Njg0NjQyOS1hMTQyLTQ0ZmQtODQxNS04YmM3OTczY2NkMTQiLCJpc3MiOiJiZy1zYW1wbGUtaXNzdWVyIiwiZXhwIjoxNTQzNDQ4ODQ5fQ.NLbJFb3o1EhhtWrKsx1FIB-I7BLMMoS3-SMjVAcuIMc" -X POST --data '{"items": [{"ticket_type_id": "d6e31698-5ccf-416c-8347-d4decc0c80b5", "quantity": 4}]}' http://localhost:9000/cart  --header "Content-Type: application/json" -i --header "Host: localhost:9000"
HTTP/1.1 200 OK
content-length: 1022
content-type: application/json
access-control-allow-origin: http://localhost:3000
vary: Origin
x-app-version: 0.1.0
date: Wed, 28 Nov 2018 23:34:36 GMT

{"id":"dacc8ea7-0e28-4843-85b3-b76a644bffee","date":"2018-11-28T23:33:43.350009","expires_at":"2018-11-28T23:48:43.359643","seconds_until_expiry":846,"status":"Draft","items":[{"id":"fd7aeea8-6225-4fb4-92dd-eff1789a0622","parent_id":null,"ticket_type_id":"d6e31698-5ccf-416c-8347-d4decc0c80b5","ticket_pricing_id":"3a9449fb-60a0-46c1-a3fa-5ee6d3f0bd31","quantity":4,"unit_price_in_cents":3000,"item_type":"Tickets","description":"It's my party - General Admission_1543444451","redemption_code":null},{"id":"09eb5ce4-99e6-4dfd-a075-123fecaaf5a9","parent_id":"fd7aeea8-6225-4fb4-92dd-eff1789a0622","ticket_type_id":null,"ticket_pricing_id":null,"quantity":4,"unit_price_in_cents":10,"item_type":"PerUnitFees","description":"Ticket Fees","redemption_code":null},{"id":"ca9bb4b8-97bc-4ebd-9926-f93b5d451d12","parent_id":null,"ticket_type_id":null,"ticket_pricing_id":null,"quantity":1,"unit_price_in_cents":100,"item_type":"EventFees","description":"Event Fees - It's my party","redemption_code":null}],"total_in_cents":12140}
```

Just in case I updated the order items in the cart to use different fee schedule range ids (before and after values) and it still returned 200 so not really sure what could be happening offhand. Will spend some time looking over the code just in case it's something else I'm missing. Although maybe something recent fixed it (a larger change for comps that did modify the update_quantities method did just get merged which modified how the fees were determined).

**Comment by Krakaw** [comment]
It does seem to be fixed with these latest changes. I'll close.
